create database student;
use student;
create table data (rollnumber int,studentname varchar(15));
insert into data values('1','vaishu');
insert into data values('2','harshi');
insert into data values('3','anjana');
insert into data values('4','emily');
insert into data values('5','Shakspere');
insert into data values('6','frost');
select * from data;